plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'
    implementation 'net.dv8tion:JDA:6.5.0'
}

application {
    mainClass = 'com.rugzar.discordbot.Main'
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
